"""ProgressSink: the method surface DownloadPipeline + downloader.py drive.

The rich `Dashboard` (core/dashboard.py) is the reference implementation;
the TUI provides `tui.sink.TextualSink` implementing the same surface so
TUI and CLI share one backend. This is a typing contract only — it does
not change any behavior.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from core.models import CookieState, DownloadTask


@runtime_checkable
class ProgressSink(Protocol):
    def add_task(self, task: DownloadTask) -> None: ...
    def update_task(self, task: DownloadTask) -> None: ...
    def update_progress(
        self, task: DownloadTask, done: int, total: int
    ) -> None: ...
    # Dashboard-only today (no pipeline caller); kept for full structural parity.
    def update_file_progress(
        self, task: DownloadTask, done: int, total: int
    ) -> None: ...
    def set_current_item(
        self, *, desc: str = "", author: str = "",
        index: int = 0, total: int = 0,
    ) -> None: ...
    def update_bytes_progress(
        self, bytes_done: int, bytes_total: int, name: str
    ) -> None: ...
    def clear_current_item(self) -> None: ...
    def add_bytes(self, nbytes: int) -> None: ...
    def set_status(self, message: str) -> None: ...
    def clear_status(self) -> None: ...
    def log_done(self, *args: Any, **kwargs: Any) -> None: ...
    def log_item_done(self, *args: Any, **kwargs: Any) -> None: ...
    def record_api_call(self, success: bool) -> None: ...
    def set_cookie_state(self, state: CookieState) -> None: ...
    def get_state(self) -> dict[str, Any]: ...
    def refresh(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
